# Generated by Django 4.2.11 on 2024-05-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
