# Generated by Django 4.2.11 on 2024-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0004_remove_job_location_job_job_provider_job_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
