# Generated by Django 4.2.11 on 2024-05-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0005_job_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Listing.job')),
            ],
        ),
    ]
